version: '3.8'
services:
  my-redis:
    image: redis
    container_name: my-redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  postgres:
    image: postgres
    container_name: contacts
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data