version: '0.1.0'
services:
  postgres:
    image: postgres
    container_name: contacts
    restart: on-failure
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data