"""'Init'

Revision ID: 2589f234156f
Revises: 8a84bcbaae44
Create Date: 2024-02-17 18:07:29.741822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2589f234156f'
down_revision: Union[str, None] = '8a84bcbaae44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
