"""'Init'

Revision ID: 39e8403edf1d
Revises: c525061498f9
Create Date: 2024-02-17 21:58:02.151164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e8403edf1d'
down_revision: Union[str, None] = 'c525061498f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=True))
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
