"""'Init'

Revision ID: f8fb0baf26e9
Revises: 50f843d5d1bc
Create Date: 2024-03-03 15:20:55.644464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fb0baf26e9'
down_revision: Union[str, None] = '50f843d5d1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'confirmed')
    # ### end Alembic commands ###
